import type { Prompt, Category } from "./types"

export const categories: Category[] = [
  { id: "1", name: "Image Prompts", slug: "image-prompts", icon: "ImageIcon", count: 25300 },
  { id: "2", name: "Text Prompts", slug: "text-prompts", icon: "FileText", count: 18700 },
  { id: "3", name: "Video Prompts", slug: "video-prompts", icon: "Video", count: 8200 },
  { id: "4", name: "Free Prompts", slug: "free-prompts", icon: "Gift", count: 12100 },
  { id: "5", name: "Midjourney", slug: "midjourney", icon: "Palette", count: 15800 },
  { id: "6", name: "ChatGPT", slug: "chatgpt", icon: "MessageSquare", count: 22400 },
  { id: "7", name: "DALL·E", slug: "dalle", icon: "Camera", count: 11200 },
  { id: "8", name: "Claude", slug: "claude", icon: "Brain", count: 9700 },
  { id: "9", name: "Stable Diffusion", slug: "stable-diffusion", icon: "Wand2", count: 13500 },
  { id: "10", name: "Leonardo AI", slug: "leonardo-ai", icon: "Sparkles", count: 7900 },
  { id: "11", name: "Gemini", slug: "gemini", icon: "Gemini", count: 0 },
  { id: "12", name: "Grok", slug: "grok", icon: "Grok", count: 0 },
  { id: "13", name: "FLUX", slug: "flux", icon: "Flux", count: 0 },
  { id: "14", name: "Sora", slug: "sora", icon: "Sora", count: 0 },
  { id: "15", name: "Vídeos", slug: "videos", icon: "Video", count: 0 },
]

export const samplePrompts: Prompt[] = [
  {
    id: "1",
    title: "Onça-Pintada Amazônica Cinematográfica",
    description:
      "Prompt profissional para gerar imagens ultra-realistas de onças-pintadas na floresta amazônica com qualidade cinematográfica.",
    prompt:
      "[Jaguar with green eyes stalking prey]::7 [detailed vegetation and waterfall in amazon rainforest background, cinematic shoot, ultrareal, morning light]::3 --ar 16:9 --s 400",
    price: 34.9,
    isFree: false,
    category: "midjourney",
    tags: ["natureza", "animais", "floresta", "amazônia", "cinematográfico", "ultra-realista"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 1247,
    views: 3421,
    images: ["/images/jaguar-prompt-result.png"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "2",
    title: "Gerador de Posts para Instagram",
    description: "Crie posts envolventes para Instagram com CTAs poderosos que convertem seguidores em clientes.",
    prompt:
      "Crie um post para Instagram sobre [TÓPICO] que seja envolvente e inclua um CTA forte. Use emojis relevantes e hashtags estratégicas. Mantenha o tom [CASUAL/PROFISSIONAL] e foque em [OBJETIVO].",
    price: 29.9,
    isFree: false,
    category: "chatgpt",
    tags: ["marketing", "instagram", "redes sociais", "cta", "engajamento"],
    author: "João Silva",
    authorId: "user-1",
    rating: 4.8,
    downloads: 892,
    views: 2156,
    images: ["/placeholder.svg?height=200&width=300"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    isActive: true,
    isAdminCreated: false,
  },
  {
    id: "3",
    title: "Prompt Gratuito - Logo Minimalista",
    description:
      "Prompt gratuito para criar logos minimalistas e modernos. Perfeito para startups e pequenos negócios.",
    prompt:
      "Create a minimalist logo for [COMPANY NAME] in [INDUSTRY]. Use clean lines, modern typography, and a color palette of [COLORS]. The logo should be scalable and work well in both color and monochrome versions. Style: minimal, professional, contemporary --ar 1:1",
    price: 0,
    isFree: true,
    category: "dalle",
    tags: ["logo", "design", "minimalista", "gratuito", "startup"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.6,
    downloads: 3421,
    views: 8765,
    images: ["/placeholder.svg?height=200&width=300"],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    isActive: true,
    isAdminCreated: true,
  },
  // Novos prompts gratuitos do Midjourney
  {
    id: "4",
    title: "Japanese Garden in Autumn",
    description:
      "Um jardim japonês sereno no outono com lago de carpas, casa de chá, árvores de bordo e folhas caindo.",
    prompt:
      "In autumn, a calm Japanese garden with a koi pond, tea house, maple trees, and falling leaves is depicted in a digital image with an AI art style.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["jardim", "japonês", "outono", "natureza", "zen", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 2156,
    views: 5432,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/japanese-garden-in-autumn-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "5",
    title: "Floating Island",
    description:
      "Ilhas flutuantes mágicas com artefatos antigos e ruínas em estilo high-fantasy inspirado em Final Fantasy.",
    prompt:
      "A high-fantasy art style depicts the magical geography of floating islands, magical artifacts, and ancient ruins boosted by Final Fantasy environments.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["fantasia", "ilhas", "magia", "final fantasy", "ruínas", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 1876,
    views: 4321,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/floating-island-best-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "6",
    title: "Haunted Elegance",
    description: "Mansão gótica assombrada em uma colina com lua cheia, névoa e figuras sombrias estilo Castlevania.",
    prompt:
      "A digital painting of a gothic horror mansion on a hill with a full moon, fog, and shadowy figures reminiscent of Castlevania.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["gótico", "horror", "mansão", "castlevania", "lua", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.6,
    downloads: 1543,
    views: 3876,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/haunted-elegance-midjourney-style-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "7",
    title: "An Underwater Haven",
    description: "Cena subaquática tranquila com sereia em uma rocha cercada por peixes e recifes de coral.",
    prompt:
      "A digital art style portrays a quiet underwater scene featuring a mermaid on the rock covered by fish and coral reefs. The focus is on water effects and on lighting.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["subaquático", "sereia", "coral", "oceano", "peixes", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 2234,
    views: 5123,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/an-underwater-haven-prompts-for-midjourney.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "8",
    title: "Magical Forest",
    description:
      "Floresta colorida e lúdica cheia de criaturas mágicas, rio e plantas brilhantes em estilo de videogame.",
    prompt:
      "A colorful and playful forest full of magical creatures, a river, and glowing plants, painted in a style similar to video games.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["floresta", "mágica", "criaturas", "videogame", "colorido", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 3456,
    views: 7890,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/magical-forest-best-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "9",
    title: "City of Neon",
    description: "Paisagem urbana cyberpunk noturna com arranha-céus iluminados por neon, multidões e carros voadores.",
    prompt:
      "At night, a highly detailed digital painting of an innovative cyberpunk cityscape featuring neon-lit skyscrapers, a mixed crowd, and flying cars.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["cyberpunk", "neon", "cidade", "futurista", "carros voadores", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 2987,
    views: 6543,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/city-of-neon-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "10",
    title: "A Pure Nature",
    description: "Close-up de uma gota de chuva em uma folha, enfatizando detalhes e a vegetação ao redor.",
    prompt:
      "A raindrop on a leaf is captured up close, emphasizing its thought and the greenery surrounding it, making a pure atmosphere.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["natureza", "macro", "gota", "folha", "puro", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.5,
    downloads: 1234,
    views: 2876,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/a-pure-nature-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "11",
    title: "Market Colors",
    description:
      "Mercado movimentado no Marrocos com cores vibrantes, texturas ricas e vendedor de rua em primeiro plano.",
    prompt:
      "A photo of a bustling marketplace in Morocco featuring vibrant colors, rich textures, and a street vendor in the forefront.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["mercado", "marrocos", "cores", "vendedor", "cultural", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.6,
    downloads: 1876,
    views: 4123,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/market-colors-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "12",
    title: "Grace Over the City",
    description:
      "Dançarina de ballet em um terraço urbano ao entardecer, com movimentos cheios de graça e energia dinâmica.",
    prompt:
      "An urban rooftop at dusk serves as the stage for a ballet dancer whose movements exude both grace and dynamic energy.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["ballet", "dança", "urbano", "terraço", "graça", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 2345,
    views: 5234,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/grace-over-the-city-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "13",
    title: "A Nostalgic Ride",
    description: "Retrato vintage de um carro na Route 66 com fotografia e atmosfera arenosa para um visual sonhador.",
    prompt:
      "Route 66 and a vintage-style portrait of a car, with the result of photography and sandiness for a dreamy feel.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["vintage", "route 66", "carro", "nostálgico", "sonhador", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.5,
    downloads: 1654,
    views: 3456,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/a-nostalgic-ride-best-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "14",
    title: "Dance of the Northern Lights",
    description: "Foto de longa exposição da Aurora Boreal sobre montanhas nevadas da Islândia.",
    prompt: "A long-exposure shot of the Northern Lights over snowy Icelandic mountains.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["aurora boreal", "islândia", "montanhas", "neve", "longa exposição", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 3789,
    views: 8234,
    images: [
      "https://mockey.ai/wp-content/uploads/sites/15/2023/10/dance-of-the-northern-lights-midjourney-prompt.png",
    ],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "15",
    title: "Story of Wrinkles",
    description:
      "Retrato em alta resolução de uma pessoa idosa capturando a pele, olhos expressivos e iluminação natural.",
    prompt: "An older person with a high resolution that captures the skin, expressive eyes, and natural lighting.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["retrato", "idoso", "rugas", "expressivo", "natural", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.6,
    downloads: 1432,
    views: 3123,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/story-of-wrinkles-best-midjourney-prompts.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "16",
    title: "A Delicate Beauty",
    description: "Close-up de uma teia de aranha com orvalho matinal destacando padrões complexos em alta qualidade.",
    prompt: "A close-up shot on a web with morning dew highlights the complex patterns, giving it a high quality.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["teia", "aranha", "orvalho", "macro", "padrões", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.4,
    downloads: 987,
    views: 2345,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/a-delicate-beauty-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "17",
    title: "New York Pulse",
    description:
      "Fotografia de rua em preto e branco de Nova York com o Empire State Building, capturando a vivacidade da cidade.",
    prompt:
      "A black & white street photograph of a bustling New York in conjunction with the State Building, capturing the vivacity and frenzy of the city.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["nova york", "preto e branco", "rua", "empire state", "urbano", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 2567,
    views: 5678,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/new-york-pulse-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "18",
    title: "Futuristic City",
    description:
      "Paisagem urbana futurista com arranha-céus imponentes e veículos voadores habitados por robôs e humanos diversos.",
    prompt:
      "A futuristic cityscape featuring towering skyscrapers and flying vehicles inhabited by diverse robots and humans.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["futurista", "cidade", "robôs", "veículos voadores", "sci-fi", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 3234,
    views: 7123,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/futuristic-city-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "19",
    title: "Abstract Geometry",
    description:
      "Pintura com formas geométricas fragmentadas, múltiplas perspectivas e cores suaves, inspirada no cubismo.",
    prompt:
      "A life painting with fragmented geometric shapes, multiple viewpoints, and muted colors, inspired by cubism artists Georges Braque and Pablo Picasso.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["abstrato", "geometria", "cubismo", "picasso", "braque", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.5,
    downloads: 1345,
    views: 2987,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/abstract-geometry-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "20",
    title: "Seaside Sunset",
    description:
      "Cidade costeira italiana pitoresca com edifícios vibrantes e água cintilante refletindo o pôr do sol.",
    prompt:
      "A picturesque Italian coastal town with vibrant buildings and shimmering water reflecting the sunset, featuring dappled light and visible brushstrokes.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["itália", "costa", "pôr do sol", "edifícios", "água", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 2876,
    views: 6234,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/seaside-sunset-best-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "21",
    title: "The Titans Clash",
    description: "Cavaleiro batalha contra um dragão sobre ondas rugindo, inspirado em Eugène Delacroix e Romantismo.",
    prompt: "A knight battles a dragon on a wave's roar below, inspired by Eugène Delacroix and Romanticism.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["cavaleiro", "dragão", "batalha", "romantismo", "delacroix", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 2234,
    views: 4876,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/the-titans-clash-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "22",
    title: "Abstract Expressions",
    description:
      "Pintura abstrata com pinceladas, cores vibrantes e tinta escorrendo refletindo emoções internas, inspirada em Jackson Pollock.",
    prompt:
      "An abstract painting with brush strokes, vibrant colors, and dripping paint reflecting inner emotions, inspired by Jackson Pollock.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["abstrato", "pollock", "pinceladas", "cores vibrantes", "emoções", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.6,
    downloads: 1765,
    views: 3654,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/abstract-expressions-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "23",
    title: "A Zen Garden",
    description: "Jardim Zen pacífico com cerejeiras em flor, peixes koi e uma ponte.",
    prompt: "A peaceful Zen garden featuring cherry blossom, a koi fish, and a bridge.",
    price: 0,
    isFree: true,
    category: "midjourney",
    tags: ["zen", "jardim", "cerejeira", "koi", "ponte", "gratuito"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 3456,
    views: 7234,
    images: ["https://mockey.ai/wp-content/uploads/sites/15/2023/10/a-zen-garden-midjourney-prompt.png"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "24",
    title: "Retrato Feminino Cinematográfico",
    description:
      "Prompt para criar retratos femininos ultra-realistas com iluminação suave, olhos azuis detalhados e pele cremosa. Perfeito para vídeos promocionais e conteúdo publicitário.",
    prompt:
      "A close-up of a thin well lit woman with light pink lips. soft light highlights her Pale cream white smoothe matte skin. large blue detailed eyes, The background color should be white to highlight the lips. smiling with her large eyes",
    price: 49.9,
    isFree: false,
    category: "videos",
    tags: ["retrato", "feminino", "cinematográfico", "olhos azuis", "iluminação suave", "publicitário"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 892,
    views: 2341,
    images: ["/images/woman-portrait-preview.jpg"],
    videoUrl: "https://cdn.midjourney.com/video/2a73deec-2976-4ded-8948-db50aa70f149/0.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "25",
    title: "Animação de Logo 3D",
    description: "Prompt para criar animações de logo em 3D com efeitos de partículas e transições suaves.",
    prompt:
      "3D logo animation with particle effects, smooth transitions, metallic materials, dramatic lighting --ar 16:9 --fps 24",
    price: 39.9,
    isFree: false,
    category: "videos",
    tags: ["logo", "3d", "animação", "partículas", "metalico"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 456,
    views: 1234,
    images: ["/placeholder.svg?height=200&width=300"],
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "26",
    title: "Transição de Paisagem Épica",
    description: "Prompt para criar transições cinematográficas entre paisagens naturais com movimento de câmera.",
    prompt:
      "Epic landscape transition, cinematic camera movement, golden hour lighting, mountains to ocean, drone perspective --ar 21:9 --fps 30",
    price: 44.9,
    isFree: false,
    category: "videos",
    tags: ["paisagem", "transição", "cinematográfico", "drone", "golden hour"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 678,
    views: 1876,
    images: ["/placeholder.svg?height=200&width=300"],
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
    isActive: true,
    isAdminCreated: true,
  },
  // NOVOS PROMPTS DE VÍDEO
  {
    id: "27",
    title: "Gato Caçando Pássaro no Pote",
    description:
      "Vídeo realista de um gato American Shorthair com patas brancas tentando pegar um pintassilgo amarelo que está cantando em cima de um pote de vidro. Perfeito para conteúdo fofo e viral.",
    prompt:
      "Realistic photo of an American shorthair cat with white paws, trying to catch the bird in a glass jar. The yellow finch is standing on top and singing.",
    price: 59.9,
    isFree: false,
    category: "videos",
    tags: ["gato", "pássaro", "realista", "fofo", "animais", "viral"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.8,
    downloads: 234,
    views: 567,
    images: ["/images/cat-bird-jar-preview.jpg"],
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "28",
    title: "Selfie Nuclear Apocalíptica",
    description:
      "Vídeo dramático de duas pessoas tirando selfie enquanto uma explosão nuclear acontece ao fundo. A onda de choque chega e balança seus cabelos. Ideal para conteúdo cinematográfico e impactante.",
    prompt:
      "Subject A and Subject B stand still at the center foreground, holding a phone out for a selfie. A massive mushroom cloud slowly rises in the distant background, the atmosphere tense and quiet. Both subjects brace slightly as they anticipate the blast. Suddenly, the shockwave arrives--dust sweeps past them, their hair whips backward,",
    price: 79.9,
    isFree: false,
    category: "videos",
    tags: ["apocalipse", "nuclear", "selfie", "dramático", "cinematográfico", "impactante"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 156,
    views: 432,
    images: ["/placeholder.svg?height=200&width=300"],
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
    isActive: true,
    isAdminCreated: true,
  },
  {
    id: "29",
    title: "Mão em Chamas com Motion Blur",
    description:
      "Fotografia artística de uma pessoa com a mão pegando fogo, capturada com motion blur para criar um efeito dramático e surreal. Perfeito para projetos artísticos e conceituais.",
    prompt: "photograph of a person with a burning hand, motion blur",
    price: 34.9,
    isFree: false,
    category: "videos",
    tags: ["fogo", "mão", "motion blur", "artístico", "surreal", "conceitual"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.7,
    downloads: 89,
    views: 234,
    images: ["/placeholder.svg?height=200&width=300"],
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4", // Usando URL externa válida
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
    isActive: true,
    isAdminCreated: true,
  },
  // NOVO PROMPT SUPER SAIYAN
  {
    id: "30",
    title: "Super Saiyan Mulher em Batalha",
    description:
      "Vídeo cinematográfico épico de uma mulher Super Saiyan em meio à batalha, concentrando energia. Tomada em ângulo amplo com efeitos visuais impressionantes de poder e transformação. Perfeito para conteúdo de anime e fantasia.",
    prompt: "wide angle cinematic shot of super saiyan woman mid-battle. powering up.",
    price: 89.9,
    isFree: false,
    category: "videos",
    tags: ["super saiyan", "anime", "batalha", "cinematográfico", "poder", "transformação", "fantasia"],
    author: "Admin Reprompt",
    authorId: "admin-1",
    rating: 4.9,
    downloads: 45,
    views: 123,
    images: ["/images/super-saiyan-woman-preview.jpg"],
    videoUrl: "https://cdn.midjourney.com/video/2a73deec-2976-4ded-8948-db50aa70f149/0.mp4",
    createdAt: new Date("2024-01-27"),
    updatedAt: new Date("2024-01-27"),
    isActive: true,
    isAdminCreated: true,
  },
]
